Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2024-12, with the labels that each got.

#754 chore: dynamic plugins are all now expressed as wrappers (RHIDP-5103)
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: Peer review needed :book:, Ready to merge :guard:, QE review not necessary, SME review not necessary

#753 chore: dynamic plugins are all now expressed as wrappers (RHIDP-5103)
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: Peer review needed :book:, Ready to merge :guard:, QE review not necessary, SME review not necessary

#757 RHIDP-4409: update metric monitoring instructions for OCP and AKS
  assemblies/assembly-monitoring-and-logging-aks.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-helm.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
  modules/observe/proc-configure-annotations-for-aks-monitoring.adoc
  modules/observe/proc-enabling-azure-monitor-metrics.adoc
  modules/observe/proc-rhdh-monitoring-logging-aks.adoc
  modules/observe/proc-view-logs-aks.adoc
  titles/monitoring-and-logging/master.adoc
Labels: QE review done :sunny:, Ready to merge :guard:, Peer review done :blue_book:, SME review not necessary

#741 RHIDP-4506: Docs sample for 'default.main-menu-items' is missing 'menuItems' field
  modules/customization/proc-customize-rhdh-sidebar-menuitems.adoc
Labels: QE review done :sunny:, Peer review needed :book:, SME review done :partly_sunny:, Ready to merge :guard:, lgtm

#773 fix: update release 1.3.1 release notes
  assemblies/assembly-release-notes-known-issues.adoc
  modules/release-notes/single-source-release-notes.jira2asciidoc.yml
  modules/release-notes/snip-known-issue-rhidp-3396.adoc
Labels: No reviews required

#774 chore: fix known issues search string
  modules/release-notes/single-source-release-notes.jira2asciidoc.yml
Labels: No reviews required

#767 RHIDP-4805: RHBK v24 support for RHDH 1.4
  artifacts/attributes.adoc
  assemblies/assembly-authenticating-with-rhbk.adoc
  assemblies/assembly-authenticating-with-rhsso.adoc
  assemblies/assembly-enabling-authentication.adoc
  modules/authentication/proc-creating-a-custom-transformer-to-provision-users-from-rhbk-to-the-software-catalog.adoc
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
  modules/authentication/proc-provisioning-users-from-rhbk-to-the-software-catalog.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#735 RHIDP-4572: Updating /metrics port
  modules/observe/proc-rhdh-monitoring-logging-aws.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary

#700 chore(installation): remove non-OLM installation doc; add link to OLM quickstart (RHIDP-2707) (RHIDP-3497)
  modules/installation/proc-rhdh-deploy-eks-operator.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary

#780 Manual cherrypicking for PR-741
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc
Labels: Ready to merge :guard:

#783 Add supported keycloak version
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#787 Add keycloak plugin 1.4
  artifacts/attributes.adoc
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#785 RHIDP-4868: Improving doc quality for Permission Policies in RHDH
  modules/authorization/ref-rbac-permission-policies.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#794 Add keycloak plugin 1.4 787
  artifacts/attributes.adoc
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-user.adoc
Labels: Ready to merge :guard:, No reviews required

#799 Sanity check 1.4 title
  modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
Labels: Ready to merge :guard:, No reviews required

#731 chore(release notes): 1.3.2/1.3.3 release notes (RHIDP-4909)
  artifacts/attributes.adoc
  assemblies/assembly-release-notes-fixed-issues.adoc
  assemblies/assembly-release-notes-fixed-security-issues.adoc
  assemblies/assembly-release-notes-known-issues.adoc
  modules/release-notes/list-fixed-security-issues-in-product-1.3.3.txt
  modules/release-notes/list-fixed-security-issues-in-rpm-1.3.3.txt
  modules/release-notes/snip-bug-fix-rhidp-5121.adoc
  modules/release-notes/snip-fixed-security-issues-in-product-1.3.3.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.3.3.adoc
Labels: lgtm :+1:, Peer review needed :book:, SME review done :partly_sunny:, Ready to merge :guard:, QE review not necessary

#766 RHIDP-4802 - Dynamic plugin: Document how users can add middleware functions to proxy backend
  assemblies/dynamic-plugins/assembly-configuring-rhdh-plugins.adoc
  modules/dynamic-plugins/con-overriding-core-backend-services.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#797 chore(dynamic plugins table): move dynamic plugin wrappers to TP (RHIDP-5103)
  assemblies/dynamic-plugins/assembly-reference-rhdh-plugins.adoc
  assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#805 chore(dynamic plugins): fix scope references for rhdh-plugins: should be @red-hat-developer-hub/ not @red/hat-developer-hub-
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: SME review done :partly_sunny:, Peer review done :blue_book:, QE review not necessary

#806 chore(dynamic plugins): fix scope references for rhdh-plugins: should be @red-hat-developer-hub/ not @red/hat-developer-hub-
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: SME review done :partly_sunny:, Peer review done :blue_book:, QE review not necessary

#810 chore(supported versions): ocp 4.17 is now...
  artifacts/attributes.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, lgtm

#809 chore(support): minimum supported OCP version is 4.14, not 4.16
  artifacts/attributes.adoc
Labels: lgtm :+1:, QE review done :sunny:, SME review done :partly_sunny:

#808 chore(support): minimum supported OCP version is 4.14, not 4.16
  artifacts/attributes.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, lgtm

#758 Release notes for Red Hat Developer Hub 1.4- Update Release Note Texts
  artifacts/attributes.adoc
  assemblies/assembly-release-notes-fixed-issues.adoc
  assemblies/assembly-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/ref-release-notes-technology-preview.adoc
Labels: Peer review needed :book:, QE review needed :wrench:, SME review needed :nut_and_bolt:

#724 Updated about RHDH and added RHTAP content
  artifacts/attributes.adoc
  assemblies/assembly-about-rhdh.adoc
  modules/about/con-benefits-of-rhdh.adoc
  modules/about/con_integrations-in-rhdh.adoc
Labels: Peer review done :blue_book:, QE review needed :wrench:, SME review needed :nut_and_bolt:, lgtm

#814 RHIDP-4585-Release-Notes-1.4-Final-Fixes
  artifacts/attributes.adoc
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/ref-release-notes-technology-preview.adoc
Labels: Peer review needed :book:, do-no-merge/review-in-progress :eyes:

#819 RHDHBUGS-137 fix the container version in the airgap with helm procedure
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
Labels: SME review needed :nut_and_bolt:, lgtm

#818 RHIDP-4490: Introduce `pluginsWithPermission` information
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
  modules/authorization/proc-rbac-ui-create-role.adoc
  modules/authorization/proc-rbac-ui-edit-role.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#817 RHIDP-5349: incorrect ID of RBAC plugin
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:
