Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2024-06, with the labels that each got.

#249 RHIDP-2256: change Topology tab to view
  modules/installation/proc-add-custom-app-config-file-ocp.adoc
  modules/installation/proc-install-rhdh-ocp-operator.adoc
Labels: lgtm

#247 RHIDP-2062: Align text and code snippet
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
Labels: lgtm

#217 RHIDP-2264 : add extra app-config configuration for AKS Operator installation procedure
  modules/admin/proc-rhdh-deploy-aks-using-operator.adoc
Labels: do-no-merge/review-in-progress

#233 RHIDP-1918: updated the customzing theme section for a note
  modules/proc-customizing-the-web-console.adoc
Labels: lgtm

#248 RHIDP-2255: clarify custom resource information
  images/rhdh/operator-install-3.png
  modules/installation/proc-config-dynamic-plugins-rhdh-operator.adoc
Labels: lgtm

#221 RHIDP-2249: Sizing for RHDH
  modules/installation/ref-rhdh-sizing.adoc
  titles/getting-started-rhdh/title-getting-started.adoc
Labels: do-no-merge/review-in-progress

#282 RHIDP-2579: Update techdocs plugin to enabled by default
  modules/dynamic-plugins/rhdh-supported-plugins.adoc
Labels: lgtm

#290 RHIDP-2011: Remove screenshot and general cleanup
  images/rhdh/screenshot-plugin-list.png
  modules/dynamic-plugins/proc-viewing-installed-plugins.adoc
Labels: lgtm

#261 RHIDP-1919 Release notes for Red Hat Developer Hub 1.2
  artifacts/attributes.adoc
  modules/release-notes/con-breaking-changes.adoc
  modules/release-notes/con-release-notes-overview.adoc
  modules/release-notes/con-relnotes-fixed-issues.adoc
  modules/release-notes/con-relnotes-known-issues.adoc
  modules/release-notes/con-relnotes-notable-features.adoc
Labels: do-not-merge/work-in-progress

#312 [1.2.x] RHIDP-1582: Add docs for enabling metrics collection
  artifacts/attributes.adoc
  assemblies/assembly-rhdh-observability.adoc
  images/rhdh/helm-upgrade.png
  images/rhdh/upgrade-helm-metrics.png
  modules/observability/proc-admin-enabling-metrics-ocp-helm.adoc
  modules/observability/proc-admin-enabling-metrics-ocp-operator.adoc
  titles/admin-rhdh/title-admin.adoc
Labels: lgtm

#326 RHIDP-1921-1 Document Known issues and fixed issues in RHDH 1.2 (edits)
  modules/release-notes/con-breaking-changes.adoc
  modules/release-notes/con-relnotes-fixed-issues.adoc
  modules/release-notes/con-relnotes-techpreview-features.adoc
Labels: lgtm

#331 RHIDP-2942: Fix link errors causing build failures
  modules/admin/proc-rhdh-monitoring-logging-aks.adoc
  modules/admin/proc-using-azure-auth-provider.adoc
Labels: lgtm

#338 Scaffolder field extension option
  modules/release-notes/con-relnotes-notable-features.adoc
Labels: lgtm

#340 docs(known-issues): Document that rollbacks are not supported
  modules/release-notes/con-relnotes-known-issues.adoc
Labels: lgtm

#345 RHIDP-3008: Add docs PR github template
  .github/pull_request_template.md
Labels: lgtm
