Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2024-11, with the labels that each got.

#649 RHIDP-4533 test documentation for style in GitHub pull requests
  .github/workflows/style-guide.yml
  .gitignore
  .vale-styles/DeveloperHub/tests/.vale.ini
  .vale.ini
  assemblies/images
  titles/plugin-rhdh/admin
  titles/plugin-rhdh/getting-started
  titles/plugin-rhdh/installation
Labels: Ready to merge :guard:, Peer review done :blue_book:

#646 RHIDP-1925 Fix GitHub integration procedure
  assemblies/assembly-authenticating-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/importing-repositories/procedure-enabling-the-bulk-import-from-github-feature.adoc
  modules/importing-repositories/procedure-importing-multiple-repositories-from-github.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#632 RHIDP-3971 authorization introduction
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  modules/authorization/con-rbac-overview.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#650 RHIDP-4529 Build documentation previews on GitHub with ccutil
  .github/workflows/build-asciidoc.yml
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#631 RHIDP-3972 RHIDP-3973 Enabling and giving access to the Role-Based Access Control (RBAC) feature
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  modules/authorization/con-rbac-config-permission-policies-admin.adoc
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#633 RHIDP-3974 managing authorization using the Web UI
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  assemblies/assembly-managing-authorizations-by-using-the-rhdh-web-ui.adoc
  modules/authorization/proc-rbac-ui-create-role.adoc
  modules/authorization/proc-rbac-ui-delete-role.adoc
  modules/authorization/proc-rbac-ui-edit-role.adoc
  modules/authorization/proc-rbac-ui-manage-roles.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#619 Create new Discover category and titles
  assemblies/assembly_about-rhdh.adoc
  titles/discover/artifacts
  titles/discover/assemblies
  titles/discover/docinfo.xml
  titles/discover/images
  titles/discover/master.adoc
  titles/discover/modules
Labels: Ready to merge :guard:

#658 RHIDP-4725: Update OCP supported versions for 1.4
  artifacts/attributes.adoc
  modules/installation/proc-install-operator.adoc
Labels: lgtm :+1:, QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#679 PR-607 redone to avoid merge conflicts
  artifacts/attributes.adoc
  artifacts/rhdh-plugins-reference/tekton/tekton-plugin-admin.adoc
  artifacts/rhdh-plugins-reference/tekton/tekton-plugin-readme.adoc
  modules/admin/proc-rhdh-monitoring-logging-aks.adoc
  modules/admin/proc-using-azure-auth-provider.adoc
  modules/authorization/proc-mounting-the-policy-csv-file-using-helm.adoc
  modules/authorization/proc-mounting-the-policy-csv-file-using-the-operator.adoc
  modules/authorization/proc-rbac-send-request-rbac-rest-api.adoc
  modules/getting-started/proc-customize-rhdh-homepage.adoc
  modules/getting-started/proc-customize-rhdh-learning-paths.adoc
  modules/getting-started/proc-customize-rhdh-tech-radar-page.adoc
  modules/getting-started/proc-enable-servicenow-custom-actions-plugin.adoc
  modules/installation/proc-enable-signin.adoc
  modules/upgrade/proc-upgrade-rhdh-operator.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#663 Adds benefits of rhdh
  assemblies/assembly-about-rhdh.adoc
  assemblies/assembly_about-rhdh.adoc
  modules/discover/con-benefits-of-rhdh.adoc
  titles/discover/master.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary

#682 chore(dynamic plugin version checking): quieter output when the versions match
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#683 chore(dynamic plugin version checking): quieter output when the versions match
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#676 RHIDP 3742-Discover-Correct Book Title
  jira2asciidoc.yml
  titles/discover/docinfo.xml
  titles/discover/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#686 chore: tweak the help message to adopt the latest example branch name (release-1.y); also make output a bit quieter and fix a bug in the plugin naming for wrapped janus idp plugins
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.template.adoc
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: lgtm :+1:, Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#688 RHIDP 3742-Discover-Correct Title
  jira2asciidoc.yml
  titles/discover/docinfo.xml
  titles/discover/master.adoc
Labels: Peer review needed :book:, lgtm, QE review not necessary, SME review not necessary

#690 RHIDP-4860 Remove Azure authentication provider from admin guide
  assemblies/assembly-rhdh-integration-aks.adoc
  modules/admin/proc-using-azure-auth-provider.adoc
Labels: Peer review needed :book:, Ready to merge :guard:, QE review not necessary, SME review not necessary

#699 chore(release notes): add two more CVEs...
  modules/release-notes/list-fixed-security-issues-in-product-1.3.1.txt
  modules/release-notes/snip-fixed-security-issues-in-product-1.3.1.adoc
Labels: lgtm :+1:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary

#681 RHIDP-4684 Update Keycloak configuration instructions
  modules/authentication/proc-enabling-authentication-with-rhsso.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#689 RHIDP-4814: Move observe related content to new titles
  artifacts/attributes.adoc
  assemblies/assembly-audit-log.adoc
  assemblies/assembly-rhdh-integration-aks.adoc
  assemblies/assembly-rhdh-integration-aws.adoc
  assemblies/assembly-rhdh-observability.adoc
  assemblies/assembly-rhdh-telemetry.adoc
  modules/observe/con-audit-log-config.adoc
  modules/observe/con-audit-log-track-changes-catalog.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-helm.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
  modules/observe/proc-audit-log-view.adoc
  modules/observe/proc-customizing-telemetry-segment-using-helm.adoc
  modules/observe/proc-customizing-telemetry-segment-using-operator.adoc
  modules/observe/proc-disabling-telemetry-using-helm.adoc
  modules/observe/proc-disabling-telemetry-using-operator.adoc
  modules/observe/proc-enabling-telemetry-using-helm.adoc
  modules/observe/proc-enabling-telemetry-using-operator.adoc
  modules/observe/proc-rhdh-monitoring-logging-aks.adoc
  modules/observe/proc-rhdh-monitoring-logging-aws.adoc
  modules/observe/ref-audit-log-catalog-events.adoc
  modules/observe/ref-audit-log-fields.adoc
  modules/observe/ref-audit-log-file-rotation-overview.adoc
  modules/observe/ref-audit-log-scaffolder-events.adoc
  modules/observe/ref-customizing-telemetry-segment.adoc
  modules/observe/ref-disabling-telemetry.adoc
  modules/observe/ref-enabling-telemetry.adoc
  titles/admin-rhdh/title-admin.adoc
  titles/audit-log/artifacts
  titles/audit-log/assemblies
  titles/audit-log/docinfo.xml
  titles/audit-log/images
  titles/audit-log/master.adoc
  titles/audit-log/modules
  titles/getting-started-rhdh/title-getting-started.adoc
  titles/monitoring-and-logging/artifacts
  titles/monitoring-and-logging/assemblies
  titles/monitoring-and-logging/docinfo.xml
  titles/monitoring-and-logging/images
  titles/monitoring-and-logging/master.adoc
  titles/monitoring-and-logging/modules
  titles/telemetry/artifacts
  titles/telemetry/assemblies
  titles/telemetry/docinfo.xml
  titles/telemetry/images
  titles/telemetry/master.adoc
  titles/telemetry/modules
Labels: Ready to merge :guard:, Peer review done :blue_book:

#529 Rhidp 3835 home page document how users can customize the home page
  assemblies/assembly-customizing-the-quick-access-card-in-rhdh.adoc
  assemblies/assembly-customizing-the-rhdh-homepage.adoc
  modules/getting-started/proc-customizing-the-home-page-cards.adoc
  modules/getting-started/proc-defining-the-layout-of-the-product-home-page.adoc
  modules/getting-started/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc
  modules/getting-started/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  titles/getting-started-rhdh/title-getting-started.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#707 RHIDP 3835 Home Page document how users can customize the home page-pr529
  assemblies/assembly-customizing-the-quick-access-card-in-rhdh.adoc
  assemblies/assembly-customizing-the-rhdh-homepage.adoc
  modules/getting-started/proc-customizing-the-home-page-cards.adoc
  modules/getting-started/proc-defining-the-layout-of-the-product-home-page.adoc
  modules/getting-started/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc
  modules/getting-started/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  titles/getting-started-rhdh/title-getting-started.adoc
Labels: Ready to merge :guard:

#685 RHIDP-3975 Managing authorization using the REST API
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  assemblies/assembly-managing-authorizations-by-using-the-rest-api.adoc
  modules/authorization/con-rbac-rest-api.adoc
  modules/authorization/proc-rbac-send-request-rbac-rest-api.adoc
  modules/authorization/proc-sending-request-to-the-rbac-rest-api-by-using-a-rest-client.adoc
  modules/authorization/proc-sending-request-to-the-rbac-rest-api-by-using-curl.adoc
  modules/authorization/snip-finding-bearer-token.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#710 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#692 RHIDP-4323: OCM permissions require additional permissionsto fully restrict resources
  modules/authorization/ref-rbac-permission-policies.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#695 RHIDP-3334: apiversion and kind update
  modules/installation/proc-add-custom-app-config-file-ocp-operator.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#713 [release-1.3] Adds benefits of rhdh #684- Updates the module titles
  titles/discover/docinfo.xml
  titles/discover/master.adoc
Labels: Ready to merge :guard:

#720 RHIDP-3975 Managing authorization using the REST API (#685)
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  assemblies/assembly-managing-authorizations-by-using-the-rest-api.adoc
  modules/authorization/con-rbac-rest-api.adoc
  modules/authorization/proc-rbac-send-request-rbac-rest-api.adoc
  modules/authorization/proc-sending-request-to-the-rbac-rest-api-by-using-a-rest-client.adoc
  modules/authorization/proc-sending-request-to-the-rbac-rest-api-by-using-curl.adoc
  modules/authorization/snip-finding-bearer-token.adoc
Labels: Ready to merge :guard:

#722 RHIDP-4814: Move observe related content to new titles (#689)
  artifacts/attributes.adoc
  assemblies/assembly-audit-log.adoc
  assemblies/assembly-rhdh-integration-aks.adoc
  assemblies/assembly-rhdh-integration-aws.adoc
  assemblies/assembly-rhdh-observability.adoc
  assemblies/assembly-rhdh-telemetry.adoc
  modules/observe/con-audit-log-config.adoc
  modules/observe/con-audit-log-track-changes-catalog.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-helm.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
  modules/observe/proc-audit-log-view.adoc
  modules/observe/proc-customizing-telemetry-segment-using-helm.adoc
  modules/observe/proc-customizing-telemetry-segment-using-operator.adoc
  modules/observe/proc-disabling-telemetry-using-helm.adoc
  modules/observe/proc-disabling-telemetry-using-operator.adoc
  modules/observe/proc-enabling-telemetry-using-helm.adoc
  modules/observe/proc-enabling-telemetry-using-operator.adoc
  modules/observe/proc-rhdh-monitoring-logging-aks.adoc
  modules/observe/proc-rhdh-monitoring-logging-aws.adoc
  modules/observe/ref-audit-log-catalog-events.adoc
  modules/observe/ref-audit-log-fields.adoc
  modules/observe/ref-audit-log-file-rotation-overview.adoc
  modules/observe/ref-audit-log-scaffolder-events.adoc
  modules/observe/ref-customizing-telemetry-segment.adoc
  modules/observe/ref-disabling-telemetry.adoc
  modules/observe/ref-enabling-telemetry.adoc
  titles/admin-rhdh/title-admin.adoc
  titles/audit-log/artifacts
  titles/audit-log/assemblies
  titles/audit-log/docinfo.xml
  titles/audit-log/images
  titles/audit-log/master.adoc
  titles/audit-log/modules
  titles/getting-started-rhdh/title-getting-started.adoc
  titles/monitoring-and-logging/artifacts
  titles/monitoring-and-logging/assemblies
  titles/monitoring-and-logging/docinfo.xml
  titles/monitoring-and-logging/images
  titles/monitoring-and-logging/master.adoc
  titles/monitoring-and-logging/modules
  titles/telemetry/artifacts
  titles/telemetry/assemblies
  titles/telemetry/docinfo.xml
  titles/telemetry/images
  titles/telemetry/master.adoc
  titles/telemetry/modules
Labels: Ready to merge :guard:

#711 RHIDP-4570: Document how to send RHDH audit logs to Splunk
  artifacts/attributes.adoc
  assemblies/assembly-audit-log.adoc
  modules/observe/proc-forward-audit-log-splunk.adoc
Labels: Ready to merge :guard:

#723 RHIDP-4998- Renames Discover Title
  assemblies/assembly-about-rhdh.adoc
  modules/about/con-benefits-of-rhdh.adoc
  titles/about/artifacts
  titles/about/assemblies
  titles/about/docinfo.xml
  titles/about/images
  titles/about/master.adoc
  titles/about/modules
Labels: Ready to merge :guard:, Peer review done :blue_book:

#709 [RHDHBUGS-106][RHIDP-4646] Clarify the behavior of the `NO_PROXY` rules
  assemblies/assembly-running-rhdh-behind-a-proxy.adoc
  modules/admin/procedure-understanding-no-proxy.adoc
Labels: QE review done :sunny:, Ready to merge :guard:, Peer review done :blue_book:, SME review not necessary

#704 RHID-3976 Managing authorization by importing external files
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  assemblies/assembly-managing-authorizations-by-using-external-files.adoc
  assemblies/assembly-managing-authorizations-by-using-the-rhdh-web-ui.adoc
  modules/authorization/con-rbac-config-permission-policies-external-file.adoc
  modules/authorization/con-rbac-config-permission-policies.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc
  modules/authorization/proc-mounting-the-policy-csv-file-using-helm.adoc
  modules/authorization/proc-mounting-the-policy-csv-file-using-the-operator.adoc
  modules/authorization/proc-rbac-config-conditional-policy-file.adoc
  modules/authorization/ref-rbac-conditional-policy-definition.adoc
  modules/authorization/ref-rbac-permission-policies.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#705 RHIDP-4896 Determining the permission policy configuration source
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  modules/authorization/proc-determining-permission-policy-and-role-configuration-source.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#728 RHID-3976 Managing authorization by importing external files (#704)
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  assemblies/assembly-managing-authorizations-by-using-external-files.adoc
  modules/authorization/con-rbac-config-permission-policies-external-file.adoc
  modules/authorization/con-rbac-config-permission-policies.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc
  modules/authorization/proc-rbac-config-conditional-policy-file.adoc
  modules/authorization/ref-rbac-conditional-policy-definition.adoc
  modules/authorization/ref-rbac-permission-policies.adoc
Labels: Ready to merge :guard:

#730 Updated 1.3 attribute
  artifacts/attributes.adoc
Labels: No reviews required

#715 RHIDP-1923 - GKE: Document how RHDH can be installed in GKE
  assemblies/assembly-audit-log.adoc
  assemblies/assembly-rhdh-integration-aks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-gke-helm.adoc
  modules/installation/proc-rhdh-deploy-gke-operator.adoc
  modules/observe/con-audit-log-config.adoc
  titles/install-rhdh-gke/artifacts
  titles/install-rhdh-gke/assemblies
  titles/install-rhdh-gke/docinfo.xml
  titles/install-rhdh-gke/images
  titles/install-rhdh-gke/master.adoc
  titles/install-rhdh-gke/modules
Labels: QE review done :sunny:, Peer review needed :book:, SME review done :partly_sunny:

#708 RHIDP-4862 - Update Tech Radar to 1.0
  modules/getting-started/proc-customize-rhdh-tech-radar-page.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:

#648 RHIDP 4573 Discover- Verify existing content is removed from the getting started guide
  modules/getting-started/ref-rhdh-sizing.adoc
  modules/installation/con-rhdh-overview.adoc
  modules/release-notes/con-release-notes-overview.adoc
  titles/getting-started-rhdh/title-getting-started.adoc
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#661 Adds supported platforms
  artifacts/attributes.adoc
  assemblies/assembly-about-rhdh.adoc
  modules/about/ref-supported-platforms.adoc
Labels: Peer review needed :book:, SME review needed :nut_and_bolt:

#743 Add supported platform
  artifacts/attributes.adoc
  modules/about/ref-supported-platforms.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#732 RHIDP-4996- Adds sizing requirements
  assemblies/assembly-about-rhdh.adoc
  modules/about/ref-rhdh-sizing.adoc
  titles/about/master.adoc
Labels: QE review done :sunny:, SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#734 RHIDP-3490-Updates the context
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#752 Resolve conflicts in PR 743
  artifacts/attributes.adoc
  assemblies/assembly-about-rhdh.adoc
  modules/about/ref-rhdh-sizing.adoc
  modules/about/ref-supported-platforms.adoc
  titles/about/master.adoc
Labels: Ready to merge :guard:

#749 Manual Cherry-pick to release-1.3-Resolve merge conflicts
  assemblies/assembly-about-rhdh.adoc
  titles/about/docinfo.xml
Labels: Ready to merge :guard:
