Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-07, with the labels that each got.

#1232 RHIDP-7812: Updated abbrev. and added missing periods
  titles/about/master.adoc
  titles/adoption-insights/master.adoc
  titles/audit-log/master.adoc
  titles/authentication/master.adoc
  titles/authorization/master.adoc
  titles/configuring/master.adoc
  titles/customizing/master.adoc
  titles/install-rhdh-air-gapped/master.adoc
  titles/install-rhdh-aks/master.adoc
  titles/install-rhdh-eks/master.adoc
  titles/install-rhdh-gke/master.adoc
  titles/install-rhdh-ocp/master.adoc
  titles/install-rhdh-osd-gcp/master.adoc
  titles/integrating-with-github/master.adoc
  titles/monitoring-and-logging/master.adoc
  titles/plugin-rhdh/title-plugin.adoc
  titles/plugins-rhdh-about/master.adoc
  titles/plugins-rhdh-configure/master.adoc
  titles/plugins-rhdh-install/master.adoc
  titles/plugins-rhdh-reference/master.adoc
  titles/plugins-rhdh-troubleshooting/master.adoc
  titles/plugins-rhdh-using/master.adoc
  titles/techdocs/docinfo.xml
  titles/telemetry/master.adoc
  titles/upgrade-rhdh/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1243 Minor change
  modules/customizing-templates/proc-creating-templates.adoc
Labels: Peer review needed :book:, do-no-merge/review-in-progress :eyes:

#1237 RHIDP-5612 - Fix platform related documentation for Operator
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
  modules/installation/proc-rhdh-deploy-eks-operator.adoc
  modules/installation/proc-rhdh-deploy-gke-operator.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1227 RHIDP-7833 Follow more logical user flow for authenticating with Azure
  assemblies/assembly-authenticating-with-microsoft-azure.adoc
  assemblies/assembly-enabling-authentication.adoc
  modules/authentication/con-understanding-authentication-and-user-provisioning.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authentication/proc-enabling-user-authentication-with-microsoft-azure.adoc
  modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1271 chore(rn): Security update for 1.5.3
  modules/release-notes/ref-release-notes-fixed-security-issues.adoc
Labels: lgtm

#1250 RHIDP-7789: Some docs refer to old CRD versions or deprecated CRD fields
  modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-operator-deployment.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  modules/customizing-techdocs/proc-techdocs-configure-odf-operator.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1277 chore: optionally provide more details about which plugins are missing from the .csv (RHIDP-4196)
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm
