Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-02, with the labels that each got.

#901 RHIDP-5004 remove useRedisSets
  modules/dynamic-plugins/proc-installing-and-configuring-redis-cache.adoc
Labels: Ready to merge :guard:

#905 feat: add GitHub action to generate supported plugins PR
  .github/workflows/generate-supported-plugins-pr.yml
Labels: SME review done :partly_sunny:, Ready to merge :guard:

#909 Update CVE content for release-1.3
  modules/release-notes/snip-fixed-security-issues-in-product-1.3.0.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.3.0.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.3.1.adoc
Labels: lgtm

#900 RHIDP-5765 comment out references to GitHub Enterprise
  modules/authentication/proc-enabling-authentication-with-github.adoc
Labels: Ready to merge :guard:

#877 RHDH-5561: TechDocs content restructure
  assemblies/assembly-configuring-techdocs.adoc
  modules/techdocs/con-techdocs-about.adoc
  titles/techdocs/artifacts
  titles/techdocs/assemblies
  titles/techdocs/docinfo.xml
  titles/techdocs/images
  titles/techdocs/master.adoc
  titles/techdocs/modules
Labels: Ready to merge :guard:, Peer review done :blue_book:

#915 RHIDP-5544: Changed alpha2 to alpha3 API in docs
  modules/configuring-deployment/proc-configuring-deployment-by-using-the-operator.adoc
  modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#918 Fix inconsistencies with referencing my-rhdh-secrets
  modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#873 RHIDP-5592:Wrong definition of Service Monitor for an RHDH instance by the Operator
  modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#912 RHIDP-5822 Release notes for Red Hat Developer Hub 1.3.5
  artifacts/attributes.adoc
  assemblies/assembly-release-notes-fixed-security-issues.adoc
  modules/release-notes/list-fixed-security-issues-in-product-1.3.5.txt
  modules/release-notes/list-fixed-security-issues-in-rpm-1.3.5.txt
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/single-source-release-notes.py
  modules/release-notes/snip-fixed-security-issues-in-product-1.3.5.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.3.5.adoc
Labels: do-not-merge/hold, Ready to merge :guard:, lgtm

#893 Change the layout of the next steps
  titles/about/master.adoc
Labels: Ready to merge :guard:

#931 chore: bad link in code snippet points to non-existent branch (RHIDP-3206)
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:

#725 Updated plugin doc for Argo CD Rollouts feature
  artifacts/rhdh-plugins-reference/argocd/argocd-plugin-admin.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#926 RHIDP-5949: Rectified the correct case for sidebarBackgroundColor
  modules/customizing-the-appearance/ref-customize-rhdh-default-rhdh.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#945 RHIDP-3206: Added missing attribute declaration in the source code
  modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc
  modules/configuring-external-databases/proc-migrating-databases-to-an-external-server.adoc
  modules/dynamic-plugins/proc-create-plugin-tgz-file.adoc
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#946 RHIDP-3206: Added attribute declaration to the relevant source code block
  modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc
  modules/configuring-external-databases/proc-migrating-databases-to-an-external-server.adoc
  modules/dynamic-plugins/proc-create-plugin-tgz-file.adoc
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#938 RHIDP-5901: readOnlyRootFilesystem option
  assemblies/assembly-configuring-readonlyrootfilesystem.adoc
  modules/configuring-readonlyrootfilesystem/proc-configuring-readonlyrootfilesystem-option-in-rhdh-helm-chart-deployment.adoc
  modules/configuring-readonlyrootfilesystem/proc-configuring-readonlyrootfilesystem-option-in-rhdh-operator-deployment.adoc
  modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  titles/configuring/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#882 chore: bump dynamic plugins versions in table for 1.4.2
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
Labels: Technical review done :partly_sunny:, Ready to merge :guard:

#868 Update the Helm procedure to use oc-mirror for air-gapped OCP environments
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#911 RHIDP-5618 Release notes for Red Hat Developer Hub 1.4.2
  artifacts/attributes.adoc
  assemblies/assembly-release-notes-fixed-security-issues.adoc
  modules/release-notes/list-fixed-security-issues-in-product-1.4.2.txt
  modules/release-notes/list-fixed-security-issues-in-rpm-1.4.2.txt
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/single-source-release-notes.jira2asciidoc.yml
  modules/release-notes/snip-fixed-security-issues-in-product-1.4.2.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.4.2.adoc
Labels: Ready to merge :guard:

#950 RHIDP-5768: Fix typo in 1.4 docs
  modules/release-notes/ref-release-notes-technology-preview.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#906 RHIDP-1848: Updates the setting up RBAC permission
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  assemblies/assembly-configuring-guest-access-with-rbac-ui.adoc
  modules/authorization/proc-configuring-the-RBAC-backend-plugin.adoc
  modules/authorization/proc-setting-up-the-guest-authentication-provider.adoc
Labels: Technical review done :partly_sunny:, do-no-merge/review-in-progress :eyes:, Ready to merge :guard:, Peer review done :blue_book:
