Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-06, with the labels that each got.

#1214 RHIDP-6749: RNs for 1.5.2
  modules/release-notes/ref-release-notes-fixed-issues.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1212 RHIDP-7542: Template editor updates
  modules/customizing-templates/proc-creating-templates.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1221 RHIDP-7748 - Update release version for 1.5.2
  artifacts/attributes.adoc
Labels: Ready to merge :guard:

#1186 RHIDP-6735 - Added high-level overview of auth and user provisioning
  assemblies/assembly-enabling-authentication.adoc
  modules/authentication/con-understanding-authentication-and-user-provisioning.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1233 Renamed RHTAP to RHADS
  artifacts/attributes.adoc
  modules/about/con-integrations-in-rhdh.adoc
Labels: Peer review needed :book:, do-no-merge/review-in-progress :eyes:, lgtm

#1218 RHIDP-7599: Update Template editor
  modules/customizing-templates/proc-creating-templates.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm
