Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-03, with the labels that each got.

#952 [RHIDP-5813] update scaffolder permissions table to include the scaffolder.template.management permission
  modules/authorization/ref-rbac-permission-policies.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:

#899 RHIDP-5491 configure expiry on refresh token cookie
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#925 RHIDP-5514: Floating action button
  assemblies/assembly-configuring-a-floating-action-button.adoc
  modules/configuring-a-floating-action-button/proc-configuring-floating-action-button-as-a-dynamic-plugin.adoc
  titles/customizing/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#978 RHIDP-5959 Update dangerouslyAllowSignInWithoutUserInCatalog config
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
  modules/authentication/proc-provisioning-users-from-github-to-the-software-catalog.adoc
  modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc
  modules/authentication/proc-provisioning-users-from-rhbk-to-the-software-catalog.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#982 [release-1.5] RHIDP-5959 Update dangerouslyAllowSignInWithoutUserInCatalog config
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
  modules/authentication/proc-provisioning-users-from-github-to-the-software-catalog.adoc
  modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc
  modules/authentication/proc-provisioning-users-from-rhbk-to-the-software-catalog.adoc
Labels: Ready to merge :guard:

#951 RHIDP-5423: Content for Kubernetes scaffolder actions
  assemblies/assembly-using-kubernetes-custom-actions.adoc
  assemblies/dynamic-plugins/assembly-configuring-rhdh-plugins.adoc
  modules/using-kubernetes-custom-actions/proc-enable-kubernetes-custom-actions-plugin.adoc
  modules/using-kubernetes-custom-actions/proc-using-kubernetes-custom-actions-plugin.adoc
  modules/using-kubernetes-custom-actions/ref-creating-a-template-using-kubernetes-custom-actions.adoc
  modules/using-kubernetes-custom-actions/ref-supported-kubernetes-custom-actions.adoc
  modules/using-service-now/proc-enable-servicenow-custom-actions-plugin.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#980 RHIDP-6391 Release notes script to stop using the issue title
  modules/release-notes/README.adoc
  modules/release-notes/single-source-release-notes-template.adoc.jinja
  modules/release-notes/single-source-release-notes.jira2asciidoc.yml
  modules/release-notes/single-source-release-notes.py
Labels: Peer review needed :book:, Technical review done :partly_sunny:, do-no-merge/review-in-progress :eyes:

#962 RHIDP-6130: Update docs to refer to new secret name
  modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc
  modules/dynamic-plugins/proc-install-plugins-using-custom-npm-registry.adoc
  modules/dynamic-plugins/proc-load-plugin-js-package.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#986 RHIDP-6130: Update docs to refer to new secret name
  modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc
  modules/dynamic-plugins/proc-install-plugins-using-custom-npm-registry.adoc
  modules/dynamic-plugins/proc-load-plugin-js-package.adoc
Labels: do-no-merge/review-in-progress :eyes:

#976 RHIDP-5409 update book links
  artifacts/attributes.adoc
  artifacts/rhdh-plugins-reference/argocd/argocd-plugin-admin.adoc
  artifacts/rhdh-plugins-reference/argocd/argocd-plugin-readme.adoc
  artifacts/rhdh-plugins-reference/argocd/argocd-plugin-user.adoc
  assemblies/assembly-configuring-techdocs.adoc
  assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
  modules/configuring/proc-provisioning-your-custom-configuration.adoc
  modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc
  modules/dynamic-plugins/ref-rh-compatible-plugins.adoc
  modules/importing-repositories/procedure-enabling-the-bulk-import-from-github-feature.adoc
Labels: do-no-merge/review-in-progress :eyes:

#970 RHIDP-4485: Topology plugin code block formatting
  assemblies/dynamic-plugins/assembly-using-rhdh-plugins.adoc
  assemblies/dynamic-plugins/assembly-using-topology-plugin.adoc
  modules/dynamic-plugins/proc-enable-users-to-use-topology-plugin.adoc
  modules/dynamic-plugins/proc-using-topology-plugin.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#919 RHIDP-5570 - Document that the Dynamic Plugin cache PVC is disabled by default
  modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#988 RHIDP-5605 - Plugin installation documentation improvement for adding 'forceDownload' field
  modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
  modules/dynamic-plugins/con-install-dynamic-plugin-helm.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#998 RHIDP-5570-2 - Document that the Dynamic Plugin cache PVC is disabled by default
  modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
Labels: Ready to merge :guard:

#967 RHIDP-1595: How to use HA in RHDH
  assemblies/assembly-configuring-high-availability.adoc
  assemblies/assembly-configuring-readonlyrootfilesystem.adoc
  modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-helm-chart-deployment.adoc
  modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-operator-deployment.adoc
  modules/configuring-readonlyrootfilesystem/proc-configuring-readonlyrootfilesystem-option-in-rhdh-helm-chart-deployment.adoc
  titles/configuring/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#948 RHIDP-5433: Applied modularization changes for the Customizing title
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc
  modules/customizing-the-quick-access-card/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#944 RHIDP-5881: Fix inconsistencies with referencing my-rhdh-secrets
  modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
  modules/configuring/proc-provisioning-your-custom-configuration.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  modules/customizing/proc-customizing-the-backend-secret.adoc
  modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
  modules/installation/proc-deploy-rhdh-instance-eks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
Labels: Ready to merge :guard:

#1000 RHDHPAI-596: Added content for RHDH adoption insights plugin
  artifacts/snip-developer-preview.adoc
  assemblies/assembly-adoption-insights.adoc
  modules/observe/adoption-insights/con-about-adoption-insights.adoc
  modules/observe/adoption-insights/proc-configure-adoption-insights.adoc
  modules/observe/adoption-insights/proc-filter-records-to-display-spec.adoc
  modules/observe/adoption-insights/proc-install-adoption-insights.adoc
  modules/observe/adoption-insights/proc-modify-number-of-displayed-records.adoc
  modules/observe/adoption-insights/proc-setting-duration-of-data-metrics.adoc
  modules/observe/adoption-insights/proc-using-adoption-insights.adoc
  modules/observe/adoption-insights/proc-viewing-adoption-insights-card.adoc
  modules/observe/adoption-insights/proc-viewing-searches.adoc
  modules/observe/con-audit-log-track-changes-catalog.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-helm.adoc
  titles/adoption-insights/artifacts
  titles/adoption-insights/assemblies
  titles/adoption-insights/docinfo.xml
  titles/adoption-insights/images
  titles/adoption-insights/master.adoc
  titles/adoption-insights/modules
Labels: Technical review done :partly_sunny:, do-no-merge/review-in-progress :eyes:, Peer review done :blue_book:

#914 RHIDP-5372- Fix inconsistent reference to the app config file
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authorization/proc-configuring-the-RBAC-backend-plugin.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
  modules/authorization/proc-setting-up-the-guest-authentication-provider.adoc
  modules/customizing-templates/proc-adding-templates.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-branding-logo.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-font.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-page-theme.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-palette.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  modules/customizing-the-appearance/proc-loading-custom-theme-using-dynamic-plugin.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-custom-components.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-default-backstage.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-default-rhdh.adoc
  modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
  modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc
  modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc
  modules/customizing-the-quick-access-card/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc
  modules/dynamic-plugins/con-install-dynamic-plugin-helm.adoc
  modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
  modules/dynamic-plugins/ref-example-dynamic-plugin-helm-installations.adoc
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
  modules/installation/proc-deploy-rhdh-instance-eks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
Labels: Ready to merge :guard:

#1004 RHIDP-5881: Fix inconsistencies with referencing my-rhdh-secrets #944
  modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
  modules/configuring/proc-provisioning-your-custom-configuration.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  modules/customizing/proc-customizing-the-backend-secret.adoc
  modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
  modules/installation/proc-deploy-rhdh-instance-eks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
Labels: Peer review needed :book:, Ready to merge :guard:

#1005 Rhidp 5881: Manual cherry-pick944.1.4
  modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
  modules/configuring/proc-provisioning-your-custom-configuration.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  modules/customizing/proc-customizing-the-backend-secret.adoc
  modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
  modules/installation/proc-deploy-rhdh-instance-eks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
Labels: Peer review needed :book:, Ready to merge :guard:

#954 RHIDP-5490: Configure global header in RHDH
  assemblies/assembly-configuring-the-global-header.adoc
  modules/configuring-the-global-header/proc-customize-rhdh-global-header.adoc
  modules/configuring-the-global-header/proc-mount-points.adoc
  titles/customizing/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1007 RHIDP-5372- Fix inconsistent reference to the app config file (#914)
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authorization/proc-configuring-the-RBAC-backend-plugin.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
  modules/authorization/proc-setting-up-the-guest-authentication-provider.adoc
  modules/customizing-templates/proc-adding-templates.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-branding-logo.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-font.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-page-theme.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-palette.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  modules/customizing-the-appearance/proc-loading-custom-theme-using-dynamic-plugin.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-custom-components.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-default-backstage.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-default-rhdh.adoc
  modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
  modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc
  modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc
  modules/customizing-the-quick-access-card/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc
  modules/dynamic-plugins/con-install-dynamic-plugin-helm.adoc
  modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
  modules/dynamic-plugins/ref-example-dynamic-plugin-helm-installations.adoc
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
  modules/installation/proc-deploy-rhdh-instance-eks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
Labels: Peer review needed :book:, Ready to merge :guard:

#1006 RHIDP-5372- Manual cherry-pick-1.4-Fix inconsistent reference to the app config file#914
  modules/authentication/proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authorization/proc-configuring-the-RBAC-backend-plugin.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
  modules/authorization/proc-setting-up-the-guest-authentication-provider.adoc
  modules/customizing-templates/proc-adding-templates.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-branding-logo.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-font.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-page-theme.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-palette.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  modules/customizing-the-appearance/proc-loading-custom-theme-using-dynamic-plugin.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-custom-components.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-default-backstage.adoc
  modules/customizing-the-appearance/ref-customize-rhdh-default-rhdh.adoc
  modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
  modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc
  modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc
  modules/customizing-the-quick-access-card/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc
  modules/dynamic-plugins/con-install-dynamic-plugin-helm.adoc
  modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
  modules/dynamic-plugins/ref-example-dynamic-plugin-helm-installations.adoc
  modules/installation/proc-configuring-an-rhdh-instance-with-tls-in-kubernetes.adoc
  modules/installation/proc-deploy-rhdh-instance-eks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
Labels: Peer review needed :book:, Ready to merge :guard:

#995 RHIDP-3393 - Document how users can access Plugin Marketplace in RHDH
  assemblies/dynamic-plugins/assembly-extensions-plugins.adoc
  modules/dynamic-plugins/con-catalog-searching-and-filtering.adoc
  modules/dynamic-plugins/proc-catalog-viewing.adoc
  modules/dynamic-plugins/proc-extensions-creating.adoc
  modules/dynamic-plugins/proc-extensions-disabling.adoc
  modules/dynamic-plugins/proc-extensions-managing.adoc
  modules/dynamic-plugins/proc-viewing-installed-plugins.adoc
  modules/dynamic-plugins/ref-catalog-plugin.adoc
  titles/plugins-rhdh-install/master.adoc
Labels: Peer review needed :book:, Technical review done :partly_sunny:, do-no-merge/review-in-progress :eyes:

#977 RHIDP-6323 - Dynamic Plugins - Update table of dynamic plugins for RHDH 1.5
  assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-compatible-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#979 [release-1.5] RHIDP-4741: RHDH 1.5 Release Notes
  assemblies/assembly-release-notes-fixed-security-issues.adoc
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-fixed-security-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/ref-release-notes-technology-preview.adoc
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#975 RHIDP-5422: TechDocs add-ons doc
  assemblies/assembly-configuring-techdocs.adoc
  assemblies/assembly-techdocs-addons-installing.adoc
  assemblies/assembly-techdocs-addons-removing.adoc
  assemblies/assembly-techdocs-addons-using.adoc
  assemblies/assembly-techdocs-addons.adoc
  modules/techdocs/con-techdocs-about.adoc
  modules/techdocs/proc-techdocs-addon-create.adoc
  modules/techdocs/proc-techdocs-addon-install-helm.adoc
  modules/techdocs/proc-techdocs-addon-install-operator.adoc
  modules/techdocs/proc-techdocs-addon-install-third-party.adoc
  modules/techdocs/proc-techdocs-addon-remove-helm.adoc
  modules/techdocs/proc-techdocs-addon-remove-operator.adoc
  modules/techdocs/proc-techdocs-addon-use-light-box.adoc
  modules/techdocs/proc-techdocs-addon-use-report-issue.adoc
  modules/techdocs/proc-techdocs-addon-use-text-size.adoc
  titles/customizing/master.adoc
  titles/techdocs/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#960 RHIDP-5681: Update the enabling authentication with rhbk
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1012 RHIDP-6397: Modularize air-gapped installation doc Helm
  assemblies/assembly-install-rhdh-airgapped-environment-ocp-helm.adoc
  modules/installation/proc-install-rhdh-helm-airgapped-full.adoc
  modules/installation/proc-install-rhdh-helm-airgapped-partial.adoc
  titles/install-rhdh-air-gapped/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1021 RHDHPAI-716: Changing default date value
  modules/observe/adoption-insights/proc-setting-duration-of-data-metrics.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1023 RHDHPAI-510: Adoption insights DP feature in 1.5 RNs
  modules/release-notes/ref-release-notes-developer-preview.adoc
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: do-no-merge/review-in-progress :eyes:

#1029 RHIDP-6675: Added screenshots to Extensions chapter
  images/rhdh-plugins-reference/dynatrace-certified-and-verified.png
  images/rhdh-plugins-reference/extensions-catalog-sidebar.png
  images/rhdh-plugins-reference/extensions-catalog.png
  modules/dynamic-plugins/con-catalog-searching-and-filtering.adoc
  modules/dynamic-plugins/proc-catalog-viewing.adoc
  modules/dynamic-plugins/ref-catalog-plugin.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1028 RHIDP-6674: Add screenshots to the Insights plugin docs
  images/rhdh-plugins-reference/active-users.jpg
  images/rhdh-plugins-reference/adoption-insights-catalog-entities.jpg
  images/rhdh-plugins-reference/adoption-insights-daterange.jpg
  images/rhdh-plugins-reference/adoption-insights.jpg
  modules/observe/adoption-insights/con-about-adoption-insights.adoc
  modules/observe/adoption-insights/proc-modify-number-of-displayed-records.adoc
  modules/observe/adoption-insights/proc-setting-duration-of-data-metrics.adoc
  modules/observe/adoption-insights/proc-viewing-adoption-insights-card.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1032 RHIDP-4743: Fixed links post-ga
  modules/release-notes/ref-release-notes-new-features.adoc
Labels: Peer review needed :book:
