Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-01, with the labels that each got.

#824 chore: update references to plugins to use their new locations; remove refs to plugins that can't be installed in 1.4 (Orchestrator) (RHIDP-4853, RHIDP-5349)
  modules/authentication/proc-creating-a-custom-transformer-to-provision-users-from-rhbk-to-the-software-catalog.adoc
  modules/authorization/proc-download-user-stats-rhdh.adoc
  modules/dynamic-plugins/proc-rhdh-example-external-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-rh-compatible-plugins.adoc
Labels: do-no-merge/review-in-progress :eyes:

#827 RHIDP-5367 - Missing and incorrect information in "breaking changes"
  modules/release-notes/ref-release-notes-breaking-changes.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#836 RHIDP-5456: Updated broken link Authorization Guide
  modules/authorization/proc-enabling-the-rbac-plugin.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#845 chore: remove reference to RHIDP-451 as we have closed it as obsolete
  README.adoc
Labels: Ready to merge :guard:, No reviews required

#844 chore(migration): move from janus-idp/backstage-showcase to redhat-developer/rhdh and add more plugin repo links too (RHIDP-1022)
  modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
  modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc
  modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
Labels: Peer review needed :book:, SME review done :partly_sunny:, Ready to merge :guard:

#838 RHIDP-5469 Update proc-enabling-authentication-with-github.adoc
  modules/authentication/proc-enabling-authentication-with-github.adoc
Labels: do-no-merge/review-in-progress :eyes:

#849 chore: plugin version bumps for 1.4.1
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
Labels: Ready to merge :guard:, SME review not necessary

#841 Fix attribute typo in Argo CD plugin
  artifacts/rhdh-plugins-reference/argocd/argocd-plugin-readme.adoc
  artifacts/rhdh-plugins-reference/argocd/argocd-plugin-user.adoc
Labels: do-no-merge/review-in-progress :eyes:

#833 RHIDP-5070-Update supported platforms
  assemblies/assembly-about-rhdh.adoc
  modules/about/con-integrations-in-rhdh.adoc
  modules/about/ref-customer-support-info.adoc
  modules/about/ref-supported-platforms.adoc
  titles/about/master.adoc
Labels: Ready to merge :guard:

#862 Updates the about guide
  assemblies/assembly-about-rhdh.adoc
  modules/about/con-integrations-in-rhdh.adoc
  modules/about/ref-customer-support-info.adoc
  modules/about/ref-supported-platforms.adoc
  titles/about/master.adoc
Labels: Ready to merge :guard:

#850 RHIDP-5334 - Fix rbac-policies mount path for Helm
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-helm.adoc
Labels: do-no-merge/review-in-progress :eyes:

#848 chore: release notes for 1.4.1 (replace custom/manual content with JIRA-driven RN content too)
  artifacts/attributes.adoc
  assemblies/assembly-release-notes-fixed-security-issues.adoc
  modules/release-notes/list-fixed-security-issues-in-product-1.4.1.txt
  modules/release-notes/list-fixed-security-issues-in-rpm-1.4.1.txt
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/ref-release-notes-technology-preview.adoc
  modules/release-notes/single-source-fixed-security-issues.sh
  modules/release-notes/single-source-release-notes-template.adoc.jinja
  modules/release-notes/single-source-release-notes.jira2asciidoc.yml
  modules/release-notes/single-source-release-notes.py
  modules/release-notes/snip-fixed-security-issues-in-product-1.4.1.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.4.1.adoc
Labels: Peer review done :blue_book:

#842 RHIDP-4780: Document per-ConfigMap/Secret configuration of mountPath
  artifacts/attributes.adoc
  assemblies/assembly-provisioning-a-custom-configuration.adoc
  modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
Labels: Peer review needed :book:, SME review done :partly_sunny:, do-no-merge/review-in-progress :eyes:

#714 HACDOCS-975: Adding JFrog Artifactory plugin content
  artifacts/rhdh-plugins-reference/jfrog-artifactory/jfrog-artifactory-plugin-admin.adoc
  artifacts/rhdh-plugins-reference/jfrog-artifactory/jfrog-artifactory-plugin-user.adoc
  assemblies/dynamic-plugins/assembly-configuring-rhdh-plugins.adoc
  assemblies/dynamic-plugins/assembly-using-rhdh-plugins.adoc
  images/rhdh-plugins-reference/jfrog-artifactory.png
Labels: Peer review needed :book:, SME review done :partly_sunny:, do-no-merge/review-in-progress :eyes:, QE review needed :wrench:

#840 Replace links to docs.openshift.com
  modules/installation/proc-install-operator.adoc
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-operator.adoc
  modules/installation/proc-install-rhdh-ocp-helm-cli.adoc
  modules/installation/proc-install-rhdh-ocp-helm-gui.adoc
  modules/installation/proc-install-rhdh-ocp-operator.adoc
  modules/observe/con-audit-log-config.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-helm.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
  modules/upgrade/proc-upgrade-rhdh-operator.adoc
Labels: Ready to merge :guard:

#857 chore: release notes for 1.3.4
  artifacts/attributes.adoc
  assemblies/assembly-release-notes-fixed-security-issues.adoc
  modules/release-notes/list-fixed-security-issues-in-product-1.3.4.txt
  modules/release-notes/list-fixed-security-issues-in-rpm-1.3.4.txt
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/ref-release-notes-technology-preview.adoc
  modules/release-notes/single-source-release-notes-template.adoc.jinja
  modules/release-notes/snip-fixed-security-issues-in-product-1.3.4.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.3.4.adoc
Labels: Peer review needed :book:, SME review done :partly_sunny:

#843 Fix release notes links
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
Labels: Ready to merge :guard:

#874 RHIDP-5643: Fix capitalization error
  modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary, SME review not necessary

#872 Fix some typos in RHDH documentation adocs
  artifacts/rhdh-plugins-reference/tekton/tekton-plugin-admin.adoc
  artifacts/rhdh-plugins-reference/tekton/tekton-plugin-readme.adoc
  artifacts/rhdh-plugins-reference/topology/topology-plugin-readme.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  modules/customizing-techdocs/proc-techdocs-using-odf-storage.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  modules/installation/proc-rhdh-deploy-aks-helm.adoc
  modules/installation/proc-rhdh-deploy-eks-operator.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:, lgtm, SME review not necessary

#869 [release-1.4] update RHBK config docs with security consideration
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
Labels: Ready to merge :guard:

#858 Rhidp 5375 consistent mentions to the product project
  modules/dynamic-plugins/proc-create-plugin-tgz-file.adoc
  modules/installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
  modules/installation/proc-install-rhdh-ocp-helm-cli.adoc
  modules/installation/proc-rhdh-deploy-aks-helm.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
  modules/observe/proc-forward-audit-log-splunk.adoc
  modules/proc-create-plugin.adoc
  modules/upgrade/proc-upgrade-rhdh-helm.adoc
Labels: Ready to merge :guard:

#834 chore(dynamic plugins): add missing...
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
  modules/dynamic-plugins/rhdh-supported-plugins.sh
Labels: Ready to merge :guard:

#876 RHIDP-5373: Setting baseUrl
  modules/configuring/proc-provisioning-your-custom-configuration.adoc
Labels: Ready to merge :guard:

#859 RHIDP-5374: Consistent mentions to the product custom resource
  modules/authorization/proc-defining-authorizations-in-external-files-by-using-the-operator.adoc
  modules/configuring-a-proxy/proc-configuring-proxy-in-operator-deployment.adoc
  modules/configuring-deployment/proc-configuring-deployment-by-using-the-operator.adoc
  modules/configuring-external-databases/proc-configuring-postgresql-instance-using-the-operator.adoc
  modules/configuring-external-databases/proc-migrating-databases-to-an-external-server.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  modules/customizing-techdocs/proc-techdocs-configure-odf-operator.adoc
  modules/dynamic-plugins/proc-config-dynamic-plugins-rhdh-operator.adoc
  modules/dynamic-plugins/proc-topology-configure.adoc
  modules/installation/proc-deploy-rhdh-instance-eks.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
  modules/observe/proc-admin-enabling-metrics-ocp-operator.adoc
  modules/observe/proc-customizing-telemetry-segment-using-operator.adoc
  modules/observe/proc-disabling-telemetry-using-operator.adoc
  modules/observe/proc-enabling-telemetry-using-operator.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, QE review not necessary

#887 chore: release note updates for GKE support and other misc updates
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
Labels: Ready to merge :guard:

#885 Remove link to Compatibility matrix
  modules/about/ref-supported-platforms.adoc
Labels: do-no-merge/review-in-progress :eyes:, lgtm

#894 Add the correct reference to product
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-admin.adoc
Labels: SME review done :partly_sunny:, do-no-merge/review-in-progress :eyes:, Ready to merge :guard:, Peer review done :blue_book:

#883 RHIDP-5725: Incorrect plugin name in the Customizing the Home page cards code snippet
  modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
  modules/customizing-the-home-page/proc-defining-the-layout-of-the-product-home-page.adoc
Labels: SME review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm
