Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-09, with the labels that each got.

#1346 RHDHBUGS-2000: Update the breaking change
  modules/release-notes/ref-release-notes-breaking-changes.adoc
Labels: do-no-merge/review-in-progress :eyes:, Peer review done :blue_book:, Technical review needed :nut_and_bolt:

#1343 RHIDP-8569 Fix the 3 AsciiDocDITA.TaskTitle warnings
  modules/configuring-a-floating-action-button/proc-configuring-floating-action-button-as-a-dynamic-plugin.adoc
  modules/observe/adoption-insights/proc-customize-adoption-insights.adoc
  modules/techdocs/proc-techdocs-addon-create.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1344 RHIDP-8548 Fix the 14 AsciiDocDITA.ExampleBlock errors
  modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-helm-chart-deployment.adoc
  modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-operator-deployment.adoc
  modules/configuring/proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator.adoc
  modules/configuring/proc-using-the-operator-to-run-rhdh-with-your-custom-configuration.adoc
  titles/configuring/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1359 RHDHBUGS-2005 Fixed broken links addendum
  assemblies/dynamic-plugins/assembly-extensions-plugins.adoc
  modules/about/ref-customer-support-info.adoc
  modules/authentication/proc-authenticationg-with-the-guest-user-on-a-helm-based-installation.adoc
  modules/authentication/proc-authenticationg-with-the-guest-user-on-an-operator-based-installation.adoc
  modules/authentication/proc-enabling-user-authentication-with-rhbk.adoc
  modules/configuring-the-global-header/con-quicklinks-and-starred-items-in-global-header.adoc
  modules/configuring-the-global-header/proc-enabling-quicklinks-starred-items-after-upgrade.adoc
  modules/configuring-the-quickstarts/proc-customize-rhdh-quickstart.adoc
  modules/customizing-the-quick-access-card/proc-using-a-dedicated-service-to-provide-data-to-the-quick-access-card.adoc
  modules/customizing-the-quick-access-card/proc-using-hosted-json-files-to-provide-data-to-the-quick-access-card.adoc
  modules/developer-lightspeed/proc-installing-and-configuring-lightspeed.adoc
  modules/dynamic-plugins/con-ansible-plugin-admin.adoc
  modules/dynamic-plugins/con-ansible-plugin-user.adoc
  modules/dynamic-plugins/con-ansible-plugin.adoc
  modules/dynamic-plugins/proc-extensions-creating.adoc
  modules/dynamic-plugins/proc-linking-to-source-code-editor-or-source.adoc
  modules/dynamic-plugins/ref-rh-compatible-plugins.adoc
  modules/importing-repositories/procedure-enabling-the-bulk-import-from-github-feature.adoc
  modules/installation/proc-deploy-rhdh-instance-gke.adoc
  modules/installation/proc-enable-signin.adoc
  modules/installation/proc-install-create-custom-flavor.adoc
  modules/installation/proc-install-operator.adoc
  modules/installation/proc-install-rhdh-airgapped-full-k8s-helm.adoc
  modules/installation/proc-install-rhdh-airgapped-partial-k8s-helm.adoc
  modules/installation/proc-install-rhdh-ocp-helm-gui.adoc
  modules/installation/proc-install-rhdh-ocp-operator.adoc
  modules/installation/proc-install-rhdh-operator-airgapped-partial.adoc
  modules/installation/proc-install-rhdh-osd-gcp-helm.adoc
  modules/installation/proc-install-rhdh-osd-gcp-operator.adoc
  modules/installation/proc-rhdh-deploy-aks-operator.adoc
  modules/observe/con-audit-log-config.adoc
  modules/observe/proc-view-logs-aks.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/techdocs/proc-techdocs-addon-create.adoc
  modules/techdocs/proc-techdocs-addon-install-third-party.adoc
  titles/plugins-rhdh-install/master.adoc
Labels: Peer review done :blue_book:

#1364 Manual cherry-pick-1.6-Add Sizing requirements as a prereq for RHDH installation
  modules/installation/proc-install-operator.adoc
  modules/installation/proc-install-rhdh-helm-airgapped-full.adoc
  modules/installation/proc-install-rhdh-helm-airgapped-partial.adoc
  modules/installation/proc-install-rhdh-ocp-helm-gui.adoc
  modules/installation/proc-install-rhdh-operator-airgapped-full.adoc
  modules/installation/proc-install-rhdh-operator-airgapped-partial.adoc
  modules/installation/proc-install-rhdh-osd-gcp-helm.adoc
  modules/installation/proc-install-rhdh-osd-gcp-operator.adoc
  modules/installation/proc-rhdh-deploy-aks-helm.adoc
  modules/installation/proc-rhdh-deploy-eks-helm.adoc
  modules/installation/proc-rhdh-deploy-eks-operator.adoc
  modules/installation/proc-rhdh-deploy-gke-helm.adoc
  modules/installation/proc-rhdh-deploy-gke-operator.adoc
Labels: Ready to merge :guard:

#1369 RHIDP-8567 fixed AsciiDocDITA.TaskDuplicate warnings
  assemblies/assembly-about-software-catalogs.adoc
  modules/software-catalogs/proc-searching-and-filter-software-catalogs.adoc
  modules/software-catalogs/proc-searching-and-filtering-software-catalog-items-by-kind.adoc
  modules/software-catalogs/proc-searching-and-filtering-software-catalog-items-by-using-the-filter-field.adoc
  modules/techdocs/proc-techdocs-addon-create.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1383 RHIDP-8896 - RHDH 1.7.1 - Update versions and support status in table of plugins
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
Labels: Technical review done :partly_sunny:, Ready to merge :guard:

#1388 RHIDP-8604: Release notes for Red Hat Developer Hub 1.7.1
  modules/release-notes/ref-release-notes-fixed-security-issues.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1398 Default configuration
  assemblies/assembly-configuring-default-secret-pvc-mounts.adoc
  assemblies/assembly-rhdh-default-configuration.adoc
  modules/configuring-external-databases/con-automated-operator-features.adoc
  modules/configuring-external-databases/con-configuring-default-secret-pvc-mounts.adoc
  modules/configuring-external-databases/con-default-base-urls.adoc
  modules/configuring-external-databases/con-metadata-generation.adoc
  modules/configuring-external-databases/con-multiple-resources.adoc
  modules/configuring-external-databases/proc-configuring-mount-paths.adoc
  modules/configuring-external-databases/ref-rhdh-default-configuration.adoc
  titles/configuring/master.adoc
Labels: Ready to merge :guard:

#1399 Manual cherry-pick-#1384
  assemblies/assembly-configuring-default-secret-pvc-mounts.adoc
  assemblies/assembly-rhdh-default-configuration.adoc
  modules/configuring-external-databases/con-automated-operator-features.adoc
  modules/configuring-external-databases/con-configuring-default-secret-pvc-mounts.adoc
  modules/configuring-external-databases/con-default-base-urls.adoc
  modules/configuring-external-databases/con-metadata-generation.adoc
  modules/configuring-external-databases/con-multiple-resources.adoc
  modules/configuring-external-databases/proc-configuring-mount-paths.adoc
  modules/configuring-external-databases/ref-rhdh-default-configuration.adoc
  titles/configuring/master.adoc
Labels: Ready to merge :guard:

#1396 RHIDP-7802: Adding short description to Home cards
  modules/customizing-the-home-page/proc-customizing-the-home-page-cards.adoc
Labels: do-no-merge/review-in-progress :eyes:, Peer review done :blue_book:, Technical review needed :nut_and_bolt:

#1403 RHDHBUGS-2051: Adding a new topic on adding a new llm provider
  artifacts/attributes.adoc
  assemblies/assembly-customizing-developer-lightspeed.adoc
  modules/developer-lightspeed/proc-changing-your-llm-provider.adoc
  modules/developer-lightspeed/proc-installing-and-configuring-lightspeed.adoc
Labels: Peer review needed :book:, do-no-merge/review-in-progress :eyes:, Technical review needed :nut_and_bolt:

#1410 RHDHBUGS-261: Minor fixes
  assemblies/assembly-rhdh-default-configuration.adoc
  modules/configuring-external-databases/con-mounts-for-default-secret-pvc-mounts.adoc
  modules/configuring-external-databases/con-multiple-resources.adoc
  modules/configuring-external-databases/ref-rhdh-default-configuration.adoc
Labels: Peer review needed :book:, do-no-merge/review-in-progress :eyes:

#1406 RHDIP-8198: removed obsolete doc files
  assemblies/assembly-release-notes-fixed-issues.adoc
  assemblies/assembly-release-notes-known-issues.adoc
  assemblies/assembly-rhdh-integration-aks.adoc
  assemblies/assembly-upgrade-rhdh.adoc
  assemblies/dynamic-plugins/assembly-about-rhdh-plugins.adoc
  assemblies/dynamic-plugins/assembly-reference-rhdh-plugins.adoc
  modules/configuring-external-databases/proc-mount-directories-pvcs.adoc
  modules/conscious-language.adoc
  modules/developer-lightspeed/con-openshift-ai.adoc
  modules/installation/proc-enable-signin.adoc
  modules/observe/con-audit-log-track-changes-catalog.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1417 RHDHBUGS-2051: Adding further changes
  modules/developer-lightspeed/proc-changing-your-llm-provider.adoc
  modules/developer-lightspeed/proc-installing-and-configuring-lightspeed.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:
