Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-04, with the labels that each got.

#989 RHIDP-5975 document the `includeTransitiveGroupOwnership` option
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
  modules/authorization/proc_enabling_transitive_parent_groups.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1020 RHIDP-6560: Fix unterminated open blocks
  modules/authentication/proc-enabling-authentication-with-microsoft-azure.adoc
  modules/authentication/proc-provisioning-users-from-microsoft-azure-to-the-software-catalog.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#990 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Peer review needed :book:

#1013 RHIDP-6550 Update URL for Ansible plug-ins docs
  modules/dynamic-plugins/con-ansible-plugin-admin.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#886 chore: emphasize Backstage version and dedupe the product name mentions
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1025 RHDHPAI-720: Adding more info to the app-config-dynamic.yaml file in the install section
  modules/observe/adoption-insights/proc-install-adoption-insights.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1026 RHIDP-6667: Update TechDocs add-ons doc
  assemblies/assembly-techdocs-addons-installing.adoc
  assemblies/assembly-techdocs-addons.adoc
Labels: Peer review needed :book:, Technical review done :partly_sunny:

#1033 RHIDP-3504: Update the doc on changing RHDH logo
  modules/customizing-the-appearance/proc-customize-rhdh-branding-logo.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#903 RHIDP-5604 Configuring entity tab titles and entity detail tab layout
  assemblies/assembly-customizing-the-appearance.adoc
  modules/customizing-the-appearance/proc-customizing-entity-detail-tab-layout.adoc
  modules/customizing-the-appearance/proc-customizing-entity-tab-titles.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1053 RHIDP-6845: Move dangerouslyAllowSignInWithoutUserInCatalog from Deprecated to Breaking changes section
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1054 RHIDP-6149: Supported platform list in installation docs
  modules/installation/proc-install-operator.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1071 RHIDP-6970: Fix headings in Customizing doc
  assemblies/assembly-customizing-the-appearance.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  titles/customizing/master.adoc
Labels: do-no-merge/review-in-progress :eyes:

#1040 RHIDP-5058: Update documentation references to the Ansible BU supported plug-ins
  artifacts/attributes.adoc
  assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1063 RHIDP-6423 Remove references to the custom auditor implementation
  assemblies/assembly-audit-log.adoc
  modules/observe/proc-audit-log-view.adoc
  modules/observe/proc-forward-audit-log-splunk.adoc
  modules/observe/ref-audit-log-catalog-events.adoc
  modules/observe/ref-audit-log-fields.adoc
  modules/observe/ref-audit-log-scaffolder-events.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1064 RHIDP-6760: Incorrect link in Customizing RHDH Title
  modules/configuring-the-global-header/proc-customize-rhdh-global-header.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1068 RHIDP-6499: Modularize Customizing the Learning Paths
  assemblies/assembly-customizing-the-learning-paths.adoc
  modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths.adoc
  modules/customizing-the-learning-paths/proc-customizing-the-learning-paths-by-using-a-dedicated-service.adoc
  modules/customizing-the-learning-paths/proc-customizing-the-learning-paths-by-using-hosted-json-files.adoc
  titles/customizing/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1057 chore: remove obsolete security RN files [main] (RHIDP-6000)
  assemblies/assembly-release-notes-fixed-security-issues.adoc
  modules/release-notes/list-fixed-security-issues-in-product-1.5.0.txt
  modules/release-notes/list-fixed-security-issues-in-rpm-1.5.0.txt
  modules/release-notes/ref-release-notes-fixed-security-issues.adoc
  modules/release-notes/single-source-fixed-security-issues.sh
  modules/release-notes/snip-fixed-security-issues-in-product-1.5.0.adoc
  modules/release-notes/snip-fixed-security-issues-in-rpm-1.5.0.adoc
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1083 RHIDP-7076: Changing version number for RHBK
  artifacts/attributes.adoc
  assemblies/assembly-authenticating-with-rhbk.adoc
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1078 RHDHBUGS-232: Changes to RHDH 1.5 release notes
  modules/release-notes/ref-release-notes-breaking-changes.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1056 RHIDP-6525: Modularizing Customizing
  assemblies/assembly-customizing-the-appearance.adoc
  modules/customizing-the-appearance/con-customize-rhdh-sidebar-menuitems.adoc
  modules/customizing-the-appearance/proc-configuring-dynamic-plugin-menuitem.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  modules/customizing-the-appearance/proc-modifying-or-adding-rhdh-custom-menuitem.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1060 RHDHPAI-735: Configuration info and other issues to fix
  modules/observe/adoption-insights/con-about-adoption-insights.adoc
  modules/observe/adoption-insights/proc-configure-adoption-insights.adoc
  modules/observe/adoption-insights/proc-install-adoption-insights.adoc
  modules/observe/adoption-insights/proc-viewing-adoption-insights-card.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1107 RHIDP:7239: Updated the reference for Adoption Insights
  modules/observe/adoption-insights/proc-install-adoption-insights.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1105 RHIDP-6882 - RHBK authentication: sub claim OIDC resolver is default
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1090 RHIDP-6508 - modularize _Supported ServiceNow custom actions_
  modules/using-service-now/ref-supported-servicenow-custom-actions.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1069 RHIDP-6500: Modularize customizing the Tech Radar page
  assemblies/assembly-customizing-the-tech-radar-page.adoc
  modules/customizing-the-tech-radar-page/proc-customize-rhdh-tech-radar-page.adoc
  modules/customizing-the-tech-radar-page/proc-customizing-the-tech-radar-page-by-using-a-customization-service.adoc
  modules/customizing-the-tech-radar-page/proc-customizing-the-tech-radar-page-by-using-a-json-file.adoc
  titles/customizing/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1079 RHIDP-6570: Document the permission support to RBAC plugin
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  modules/authorization/proc-delegating-rbac-access.adoc
  modules/authorization/ref-rbac-permission-policies.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1077 RHIDP-6566: Rename Create with Self-service
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc
  artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-user.adoc
  assemblies/assembly-configuring-the-global-header.adoc
  images/rhdh-plugins-reference/group1.jpg
  images/rhdh-plugins-reference/user-list.jpg
  images/rhdh-plugins-reference/user2.jpg
  images/rhdh-plugins-reference/users.jpg
  modules/configuring-the-global-header/proc-customize-rhdh-global-header.adoc
  modules/customizing-templates/proc-creating-templates.adoc
  modules/customizing-templates/ref-creating-templates.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1089 RHIDP-6507 - modularize _Monitoring and logging with AWS
  assemblies/assembly-logging-with-amazon-cloudwatch.adoc
  assemblies/assembly-monitoring-and-logging-with-aws.adoc
  assemblies/assembly-monitoring-with-amazon-prometheus.adoc
  modules/observe/proc-configuring-annotations-for-monitoring-with-amazon-prometheus-by-using-the-helm-chart.adoc
  modules/observe/proc-configuring-annotations-for-monitoring-with-amazon-prometheus-by-using-the-operator.adoc
  modules/observe/proc-configuring-the-application-log-level-for-logging-with-amazon-cloudwatch-logs-by-using-the-helm-chart.adoc
  modules/observe/proc-configuring-the-application-log-level-for-logging-with-amazon-cloudwatch-logs-by-using-the-operator.adoc
  modules/observe/proc-retrieving-logs-from-amazon-cloudwatch.adoc
  modules/observe/proc-rhdh-monitoring-logging-aws.adoc
  titles/monitoring-and-logging/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1073 RHIDP-6502 Modularize Overriding Core Backend Service Configuration
  assemblies/dynamic-plugins/assembly-configuring-rhdh-plugins.adoc
  modules/dynamic-plugins/con-overriding-core-backend-services.adoc
  modules/dynamic-plugins/proc-overriding-core-backend-services.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1096 RHIDP-6571 - remove configuring the base URL for Operator-based
  modules/configuring/proc-provisioning-your-custom-configuration.adoc
Labels: Peer review done :blue_book:, Technical review needed :nut_and_bolt:

#1065 RHIDP-6504: Modularize modules/dynamic-plugins/proc-topology-configure
  assemblies/assembly-managing-labels-annotations-topology.adoc
  assemblies/assembly-topology-plugin-configure.adoc
  assemblies/dynamic-plugins/assembly-configuring-rhdh-plugins.adoc
  assemblies/dynamic-plugins/assembly-install-topology-plugin.adoc
  modules/dynamic-plugins/proc-app-grouping.adoc
  modules/dynamic-plugins/proc-enabling-the-source-code-editor.adoc
  modules/dynamic-plugins/proc-entity-annotation-or-label.adoc
  modules/dynamic-plugins/proc-icon-displayed-in-the-node.adoc
  modules/dynamic-plugins/proc-label-selector-query-annotation.adoc
  modules/dynamic-plugins/proc-linking-to-source-code-editor-or-source.adoc
  modules/dynamic-plugins/proc-namespace-annotation.adoc
  modules/dynamic-plugins/proc-node-connector.adoc
  modules/dynamic-plugins/proc-topology-configure.adoc
  modules/dynamic-plugins/proc-viewing-openshift-routes.adoc
  modules/dynamic-plugins/proc-viewing-pod-logs.adoc
  modules/dynamic-plugins/proc-viewing-tekton-pipelineruns.adoc
  modules/dynamic-plugins/proc-viewing-virtual-machines.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1067 RHIDP-5515: Document default PVC and Secret configuration update
  assemblies/assembly-configuring-default-secret-pvc-mounts.adoc
  modules/configuring-external-databases/proc-configuring-mount-paths.adoc
  modules/configuring-external-databases/proc-mounting-to-specific-containers.adoc
  titles/configuring/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:
