Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-05, with the labels that each got.

#1086 RHIDP-6506: Modularize proc-rhdh-deploy-eks-operator.adoc
  assemblies/assembly-install-rhdh-eks-operator.adoc
  modules/installation/proc-rhdh-deploy-eks-operator.adoc
  titles/install-rhdh-eks/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1082 RHIDP-6146: Create developer-focused TechDocs content
  assemblies/assembly-techdocs-add-docs.adoc
  assemblies/assembly-using-techdocs.adoc
  modules/techdocs/proc-techdocs-add-docs-from-remote-repo.adoc
  modules/techdocs/proc-techdocs-edit-docs.adoc
  modules/techdocs/proc-techdocs-find-docs.adoc
  modules/techdocs/proc-techdocs-view-docs.adoc
  titles/techdocs/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1072 RHIDP-6850: Add TechDocs subtitle
  titles/techdocs/docinfo.xml
  titles/techdocs/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1052 RHIDP-5483: Update Authorization Preface
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  titles/authentication/master.adoc
  titles/authorization/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1087 RHIDP-6503 - Modularize: Installing and configuring the Redis cache
  modules/dynamic-plugins/proc-installing-and-configuring-redis-cache.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1034 RHIDP-5653: Reorganize Segment/Telemetry instructions into its own category
  assemblies/assembly-customizing-segment-source.adoc
  assemblies/assembly-disabling-telemetry-data-collection.adoc
  assemblies/assembly-enabling-telemetry-data-collection.adoc
  assemblies/assembly-rhdh-telemetry.adoc
  modules/analytics/con-telemetry-data-collection-and-analysis.adoc
  modules/analytics/proc-customizing-segment-source-using-helm-the-helm-chart.adoc
  modules/analytics/proc-customizing-segment-source-using-the-operator.adoc
  modules/analytics/proc-disabling-telemetry-using-helm.adoc
  modules/analytics/proc-disabling-telemetry-using-operator.adoc
  modules/analytics/proc-enabling-telemetry-using-helm.adoc
  modules/analytics/proc-enabling-telemetry-using-operator.adoc
  modules/observe/ref-customizing-telemetry-segment.adoc
  modules/observe/ref-disabling-telemetry.adoc
  titles/telemetry/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1097 RHIDP-6575 - Promote RHDH-local to Dev preview status in RHDH Docs
  artifacts/attributes.adoc
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Technical review done :partly_sunny:, do-no-merge/review-in-progress :eyes:, Peer review done :blue_book:

#1141 RHIDP-6575-1 - Promote RHDH-local to Dev preview status in RHDH Docs
  modules/release-notes/ref-release-notes-developer-preview.adoc
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Ready to merge :guard:

#1137 RHIDP-5653: Reorganize Segment/Telemetry instructions into its own ca…
  assemblies/assembly-customizing-segment-source.adoc
  assemblies/assembly-disabling-telemetry-data-collection.adoc
  assemblies/assembly-enabling-telemetry-data-collection.adoc
  assemblies/assembly-rhdh-telemetry.adoc
  modules/analytics/con-telemetry-data-collection-and-analysis.adoc
  modules/analytics/proc-customizing-segment-source-using-helm-the-helm-chart.adoc
  modules/analytics/proc-customizing-segment-source-using-the-operator.adoc
  modules/analytics/proc-disabling-telemetry-using-helm.adoc
  modules/analytics/proc-disabling-telemetry-using-operator.adoc
  modules/analytics/proc-enabling-telemetry-using-helm.adoc
  modules/analytics/proc-enabling-telemetry-using-operator.adoc
  modules/observe/ref-customizing-telemetry-segment.adoc
  modules/observe/ref-disabling-telemetry.adoc
  titles/telemetry/master.adoc
Labels: Ready to merge :guard:

#1138 RHIDP-5653: Reorganize Segment/Telemetry instructions into its own ca…
  assemblies/assembly-customizing-segment-source.adoc
  assemblies/assembly-disabling-telemetry-data-collection.adoc
  assemblies/assembly-enabling-telemetry-data-collection.adoc
  assemblies/assembly-rhdh-telemetry.adoc
  modules/analytics/con-telemetry-data-collection-and-analysis.adoc
  modules/analytics/proc-customizing-segment-source-using-helm-the-helm-chart.adoc
  modules/analytics/proc-customizing-segment-source-using-the-operator.adoc
  modules/analytics/proc-disabling-telemetry-using-helm.adoc
  modules/analytics/proc-disabling-telemetry-using-operator.adoc
  modules/analytics/proc-enabling-telemetry-using-helm.adoc
  modules/analytics/proc-enabling-telemetry-using-operator.adoc
  modules/observe/ref-customizing-telemetry-segment.adoc
  modules/observe/ref-disabling-telemetry.adoc
  titles/telemetry/master.adoc
Labels: Ready to merge :guard:

#1139 RHIDP-7116: Remove dangerouslyAllowSignInWithoutUserInCatalog in RHBK auth section
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1149 RHIDP-7116: Remove dangerouslyAllowSignInWithoutUserInCatalog in RHBK auth section
  modules/authentication/proc-enabling-authentication-with-rhbk.adoc
Labels: Ready to merge :guard:

#1070 RHIDP-6568: Create RHDH Metadata card customization content
  modules/customizing/proc-customizing-rhdh-metadata-card.adoc
  titles/customizing/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1150 RHIDP-6569-1 - Document the configurable features of navigation (sidebar) in RHDH
  modules/customizing-the-appearance/proc-configuring-dynamic-plugin-menuitem.adoc
  modules/customizing-the-appearance/proc-customize-rhdh-sidebar-menuitems.adoc
  modules/customizing-the-appearance/proc-modifying-or-adding-rhdh-custom-menuitem.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1085 RHIDP-6582 - Dynamic Plugins - Update table of dynamic plugins for RHDH 1.6
  assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
Labels: do-no-merge/review-in-progress :eyes:, Peer review done :blue_book:, Technical review needed :nut_and_bolt:, lgtm

#1155 RHIDP-6575:Minor-Fixes-RHIDP-6000-Release-notes-for-Red-Hat-Developer-Hub-1.6.0
  modules/release-notes/ref-release-notes-developer-preview.adoc
Labels: lgtm

#1099 RHIDP-6147: Developer-focused content for Learning Paths
  assemblies/assembly-customizing-the-learning-paths.adoc
  modules/customizing-the-learning-paths/con-about-learning-paths.adoc
  modules/customizing-the-learning-paths/proc-starting-and-completing-lessions-in-learning-paths.adoc
  titles/customizing/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1084 RHIDP-6584 - Document how users can install and configure plugins from Marketplace in RHDH
  assemblies/dynamic-plugins/assembly-extensions-plugins.adoc
  images/rhdh-plugins-reference/rhdh-extensions-tekton-card.png
  images/rhdh-plugins-reference/rhdh-extensions-tekton-details.png
  images/rhdh-plugins-reference/rhdh-extensions-tekton-editor-1.png
  images/rhdh-plugins-reference/rhdh-extensions-tekton-editor-2.png
  modules/dynamic-plugins/proc-extensions-installing.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1098 RHIDP-6145: Added developer-focused content for software templates
  assemblies/assembly-configuring-templates.adoc
  images/rhdh/template-creation-not-successful.png
  images/rhdh/template-creation-successful.png
  images/rhdh/template-editor.png
  modules/customizing-templates/proc-adding-templates.adoc
  modules/customizing-templates/proc-creating-a-new-software-component-using-templates.adoc
  modules/customizing-templates/proc-creating-templates.adoc
  modules/customizing-templates/proc-searching-and-filtering-software-templates.adoc
  modules/customizing-templates/ref-creating-templates.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1158 RHIDP-6152: Update Install Operator doc to reflect UI changes
  artifacts/attributes.adoc
  modules/installation/proc-install-operator.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1156 chore: update plugins list for 1.7/main, including new enabled-by-default tech preview plugins
  modules/dynamic-plugins/con-preinstalled-dynamic-plugins.adoc
  modules/dynamic-plugins/ref-community-plugins.adoc
  modules/dynamic-plugins/ref-rh-supported-plugins.adoc
  modules/dynamic-plugins/ref-rh-tech-preview-plugins.adoc
  modules/dynamic-plugins/rhdh-supported-plugins.csv
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1101 RHIDP-7038: Doc air-gapped installation on K8s platforms with Helm
  assemblies/assembly-install-rhdh-airgapped-environment-k8s-helm.adoc
  modules/installation/proc-install-rhdh-airgapped-full-k8s-helm.adoc
  modules/installation/proc-install-rhdh-airgapped-partial-k8s-helm.adoc
  titles/install-rhdh-air-gapped/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1169 RHIDP-5184 - added steps to _Configuring Redis cache_
  modules/configuring/proc-enabling-the-rhdh-plugin-assets-cache.adoc
  modules/dynamic-plugins/proc-installing-and-configuring-redis-cache.adoc
  titles/configuring/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1180 RHIDP-6498: Modularize modules/configuring-a-floating-action-button/proc-configuring-floating-action-button-as-a-dynamic-plugin.adoc
  assemblies/assembly-configuring-a-floating-action-button.adoc
  modules/configuring-a-floating-action-button/proc-configuring-floating-action-button-as-a-dynamic-plugin.adoc
  modules/configuring-a-floating-action-button/ref-floating-action-button-parameters.adoc
Labels: Ready to merge :guard:

#1179 RHIDP-6501 - Modularize modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
  assemblies/dynamic-plugins/assembly-using-the-dynamic-plugins-cache.adoc
  modules/dynamic-plugins/con-dynamic-plugins-cache.adoc
  modules/dynamic-plugins/proc-creating-a-pvc-for-the-dynamic-plugin-cache-by-using-helm.adoc
  modules/dynamic-plugins/proc-creating-a-pvc-for-the-dynamic-plugin-cache-by-using-the-operator.adoc
  modules/dynamic-plugins/ref-configuring-the-dynamic-plugins-cache.adoc
  titles/configuring/master.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1178 RHIDP-7542: Template Editor section update
  modules/customizing-templates/proc-creating-templates.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1185 RHIDP-5999: POST-GA docs release tasks for RHDH release
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
Labels: Ready to merge :guard:

#1176 RHIDP-7461: List the steps for role-based access in UI
  assemblies/assembly-configuring-authorization-in-rhdh.adoc
  assemblies/assembly-delegating-rbac-access-rhdh.adoc
  modules/authorization/proc-delegating-rbac-access-api.adoc
  modules/authorization/proc-delegating-rbac-access-webui.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1190 RHDHBUGS-241: Update RHSA links for Fixed Security Issues for 1.5
  modules/release-notes/ref-release-notes-fixed-security-issues.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1188 RHIDP-5999: Fixed Issues in RN
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
Labels: Technical review done :partly_sunny:, Peer review done :blue_book:

#1191 RHDHPAI-813: Updated the adoption insights image
  modules/observe/adoption-insights/proc-install-adoption-insights.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1206 RHIDP-7649: Update link to Bulk importing GitHub repositories
  artifacts/attributes.adoc
  modules/software-catalogs/proc-adding-new-components-to-the-rhdh-instance.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:
