Repository redhat-developer/red-hat-developers-documentation-rhdh, pull requests merged in 2025-08, with the labels that each got.

#1228 RHIDP-7202: Doc procs for generating TechDocs pipeline with GitHub Actions and embedding videos
  assemblies/assembly-configuring-techdocs.adoc
  assemblies/assembly-using-techdocs.adoc
  modules/customizing-techdocs/con-techdocs-config-cicd.adoc
  modules/customizing-techdocs/con-techdocs-configure-storage.adoc
  modules/customizing-techdocs/proc-techdocs-config-cicd-prep-repo.adoc
  modules/customizing-techdocs/proc-techdocs-generate-site.adoc
  modules/customizing-techdocs/proc-techdocs-publish-site.adoc
  modules/customizing-techdocs/proc-techdocs-using-odf-storage.adoc
  modules/techdocs/proc-techdocs-configure-amazon-s3-storage.adoc
  modules/techdocs/proc-techdocs-embed-videos.adoc
  modules/techdocs/proc-techdocs-pipeline-github-actions.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1229 RHDHPAI-804: Multi-analytics provider (Adoption Insights plugin)
  assemblies/assembly-adoption-insights.adoc
  modules/observe/adoption-insights/con-about-adoption-insights.adoc
  modules/observe/adoption-insights/proc-configure-adoption-insights.adoc
  modules/observe/adoption-insights/proc-customize-adoption-insights.adoc
  modules/observe/adoption-insights/proc-install-adoption-insights.adoc
  modules/observe/adoption-insights/proc-modify-number-of-displayed-records.adoc
  modules/observe/adoption-insights/proc-viewing-active-users.adoc
  modules/observe/adoption-insights/proc-viewing-adoption-insights-card.adoc
  modules/observe/adoption-insights/proc-viewing-top-catalog-entities.adoc
  modules/observe/adoption-insights/proc-viewing-top-plugins.adoc
  modules/observe/adoption-insights/proc-viewing-top-techdocs.adoc
  modules/observe/adoption-insights/proc-viewing-top-templates.adoc
  modules/observe/adoption-insights/proc-viewing-total-number-of-users.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1258 RHIDP-6966: use @red-hat-developer-hub/cli instead of @janus-idp/cli
  modules/dynamic-plugins/proc-create-plugin-js-package.adoc
  modules/dynamic-plugins/proc-create-plugin-oci-image.adoc
  modules/dynamic-plugins/proc-export-third-party-plugins-rhdh.adoc
  modules/dynamic-plugins/ref-example-third-party-plugin-installation.adoc
  modules/proc-create-plugin.adoc
  modules/techdocs/proc-techdocs-addon-install-third-party.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1292 Minor change in adoption insights
  assemblies/assembly-adoption-insights.adoc
Labels: do-no-merge/review-in-progress :eyes:, Peer review done :blue_book:, lgtm

#1287 RHIDP-8240 - Create a Quickstart guide to support first-time onboarding for administrators
  assemblies/assembly-configuring-the-quickstarts.adoc
  images/rhdh/about-quickstarts.png
  modules/configuring-the-quickstarts/con-about-quickstarts.adoc
  modules/configuring-the-quickstarts/proc-customize-rhdh-quickstart.adoc
  modules/configuring-the-quickstarts/proc-starting-and-completing-modules-in-quickstarts.adoc
  titles/customizing/master.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1300 RHDHPAI-808: Developer Lightspeed content RHDH
  artifacts/attributes.adoc
  artifacts/snip-developer-preview.adoc
  assemblies/assembly-appendix-about-user-data-security.adoc
  assemblies/assembly-appendix-llm-requirements.adoc
  assemblies/assembly-customizing-developer-lightspeed.adoc
  assemblies/assembly-developer-lightspeed.adoc
  assemblies/assembly-using-developer-lightspeed.adoc
  images/rhdh-plugins-reference/developer-lightspeed.png
  modules/developer-lightspeed/con-about-bring-your-own-model.adoc
  modules/developer-lightspeed/con-about-data-use.adoc
  modules/developer-lightspeed/con-about-developer-lightspeed.adoc
  modules/developer-lightspeed/con-about-feedback-collection.adoc
  modules/developer-lightspeed/con-about-road-core-service.adoc
  modules/developer-lightspeed/con-llm-requirements.adoc
  modules/developer-lightspeed/con-ollama.adoc
  modules/developer-lightspeed/con-openai.adoc
  modules/developer-lightspeed/con-openshift-ai.adoc
  modules/developer-lightspeed/con-rag-embeddings.adoc
  modules/developer-lightspeed/con-supported-architecture.adoc
  modules/developer-lightspeed/con-vllm.adoc
  modules/developer-lightspeed/con-your-responsiblity.adoc
  modules/developer-lightspeed/proc-customizing-the-chat-history-storage.adoc
  modules/developer-lightspeed/proc-gathering-feedback.adoc
  modules/developer-lightspeed/proc-installing-and-configuring-lightspeed.adoc
  modules/developer-lightspeed/proc-updating-the-system-prompt.adoc
  modules/developer-lightspeed/proc-using-developer-lightspeed-to-create-new-chats-after-the-first-chat.adoc
  modules/developer-lightspeed/proc-using-developer-lightspeed-to-delete-a-chat.adoc
  modules/developer-lightspeed/proc-using-developer-lightspeed-to-start-a-chat-for-the-first-time.adoc
  modules/developer-lightspeed/proc-using-developer-lightspeed-to-view-chat-history.adoc
  modules/developer-lightspeed/proc-using-question-validation.adoc
  titles/developer-lightspeed/artifacts
  titles/developer-lightspeed/assemblies
  titles/developer-lightspeed/docinfo.xml
  titles/developer-lightspeed/images
  titles/developer-lightspeed/master.adoc
  titles/developer-lightspeed/modules
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1303 RHIDP-6478 - Release notes for Red Hat Developer Hub 1.7.0
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-developer-preview.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/single-source-release-notes.jira2asciidoc.yml
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Ready to merge :guard:, Peer review done :blue_book:

#1314 RHIDP-6478-1 - Release notes for Red Hat Developer Hub 1.7.0
  modules/release-notes/ref-release-notes-deprecated-functionalities.adoc
  modules/release-notes/ref-release-notes-developer-preview.adoc
  modules/release-notes/ref-release-notes-fixed-issues.adoc
  modules/release-notes/ref-release-notes-known-issues.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
  modules/release-notes/single-source-release-notes.jira2asciidoc.yml
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Ready to merge :guard:

#1316 RHIDP-7723: Removing readonlyrootfilesystem
  assemblies/assembly-configuring-readonlyrootfilesystem.adoc
  modules/configuring-readonlyrootfilesystem/proc-configuring-readonlyrootfilesystem-option-in-rhdh-helm-chart-deployment.adoc
  modules/configuring-readonlyrootfilesystem/proc-configuring-readonlyrootfilesystem-option-in-rhdh-operator-deployment.adoc
  titles/configuring/master.adoc
Labels: Technical review done :partly_sunny:, do-no-merge/review-in-progress :eyes:, Peer review done :blue_book:

#1318 Orchestrator in RHDH Updates
  assemblies/assembly-install-rhdh-orchestrator.adoc
  assemblies/assembly-orchestrator-rhdh.adoc
  modules/orchestrator/con-supported-architecture-for-orchestrator.adoc
  modules/orchestrator/con-understanding-orchestrator-plugin-dependencies-operator.adoc
  modules/orchestrator/proc-enable-orchestrator-plugin.adoc
  modules/orchestrator/proc-install-components-for-orchestrator-plugin.adoc
  modules/orchestrator/proc-install-rhdh-with-orchestrator-helm-cli.adoc
  modules/orchestrator/proc-install-rhdh-with-orchestrator-helm-webui.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:, lgtm

#1325 RHIDP-6477-RN-JANUS-IDP-CLI - POST-GA docs release tasks for RHDH 1.7.0 release
  modules/release-notes/ref-release-notes-breaking-changes.adoc
  modules/release-notes/ref-release-notes-deprecated-functionalities-extra.adoc
  titles/rel-notes-rhdh/title-rhdh-release-notes.adoc
Labels: Ready to merge :guard:

#1324 RHIDP-8688: Minor changes
  artifacts/attributes.adoc
  modules/observe/adoption-insights/proc-configure-adoption-insights.adoc
  modules/observe/adoption-insights/proc-customize-adoption-insights.adoc
  modules/release-notes/ref-release-notes-new-features.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:

#1321 RHIDP-7723: Readonlyrootfilesystem release notes update
  modules/release-notes/ref-release-notes-new-features.adoc
Labels: Technical review done :partly_sunny:, Ready to merge :guard:, Peer review done :blue_book:
